### PR TITLE
Add more options for time intervals, more like Grafana

### PR DESCRIPTION
**Pull request by Frogmore42**
I always hated that emoncms used 1 week as the starting window.  I liked that you used 1 day, but I like Grafana's way of doing it better.  This makes the graph closer to the ease that Grafana has for selecting time periods.  It is still better, but this was a quick and simple change.  Tested on Edge and Android Chrome and looks good.  Should be fine on other browsers, the layout flows nicely, but is still less refined than what you get with Grafana (but making that better would be a huge change ;-)).

### CODE REVIEW

**Comment by Frogmore42** [comment]
Updated it to use a dropdown, not sure this is the best it can be, but it seems to work well.

**Comment by Frogmore42** [comment]
okay, this one works correctly now with a dropdown for the selection

**Comment by Frogmore42** [comment]
Okay it now has long arrows for the axis pointer indication, and the device name is in the title.

**Comment by boblemaire** [comment]
This has been merged.

**Pull request merged**
