### PR TITLE
Added instructions to reset the WiFi

### PR DESCRIPTION
**Pull request by iamphilrob**
Included the instructions given in the forum on resetting the Wifi into the documentation

### CODE REVIEW

**Comment by boblemaire** [comment]
Thanks, @iamphilrob .  Could you add that after the command is sent, IoTaWatt will respond "ok" and the LED will change from a dull green to a dull red when the IoTaWatt disconnects, indicating that the WiFi link has been severed?

**Comment by iamphilrob** [comment]
Done :-)

**Comment by iamphilrob** [comment]
Closed pull request in error - re-opening

**Comment by boblemaire** [comment]
Thanks Phil, will rebuild docs soon.

**Pull request merged**
